
name: CD

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  cd:

    runs-on: ubuntu-20.04

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/
            cd /var/www/samovar
            git pull
